routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Master\BarangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->group(function () {
    Route::get("/", [DashboardController::class, "index"]);
    Route::prefix("/barang")->group(function () {
        Route::get("list", [BarangController::class, "getList"]);
    });
    Route::resource('/barang', BarangController::class);


});

require __DIR__.'/auth.php';

app/Models/Barang.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Barang extends Model
{
    use SoftDeletes;
    protected $table = 'mst_barang';
    protected $primaryKey = 'id';
    public $timestamps = true;

    protected $fillable = [
        'nama_barang',
        'kode_barang',
        'stock',
        'barang_logo',
        'satuan',
        'img_barang',
        'keterangan',
        'created_by',
        'updated_by',
        'deleted_by'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index() {
        return view('index');
    }
}

app/Http/Controllers/Master/BarangController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Barang;
use App\Library\ImageUploader;


class BarangController extends Controller
{
    public function __construct(ImageUploader $imageUploader)
    {
        $this->uploader = $imageUploader;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('master.barang.index');
    }

    public function getList(Request $request){

        return datatables(Barang::query())
        ->addIndexColumn()
            ->escapeColumns([])
        ->editColumn(
            'img_barang',
            function ($data) {
                return  '<img src="' .$data->img_barang. '" width="100px">';
            }
        )
        ->addColumn('action', function ($data)   {
            $html = '';

            $html .= '<a class="btn btn-icon btn-link"   href="' . route('barang.show',  $data->id) . '"> <i class="fas fa-eye"></i></a>';



            $html .= '<a class="btn btn-icon btn-link" href="' . route('barang.edit',  $data->id) . '">
            <i class="fas fa-edit"></i></a>';

            $html .= '<a class="btn btn-icon btn-link btn-delete" id="'.$data->id.'">
            <i class="fas fa-trash"></i>
          </a>';



            return $html;
        })->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('master.barang.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $filename = $this->uploader->uploadImage($data['barang_logo'], 'master/barang');

        Barang::create([
            'nama_barang'=>$data['nama_barang'],
            'kode_barang' => "BRB/".date('YmdHis'),
            'stock' => $data['stock'],
            'satuan' => "qty",
            'keterangan' => '',
            'img_barang'=>$filename,
        ]);
        return response()->json(['status' => 'success', 'msg' => 'Data berhasil ditambahkan']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Barang::find($id);
        

        return view('master.barang.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Barang::find($id);
        return view('master.barang.edit', compact('data'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Barang::find($id);
        $data->nama_barang = $request->nama_barang;
        $data->stock = $request->stock;
        $data->save();
        return response()->json(['status' => 'success', 'msg' => 'Data berhasil ditambahkan']);
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

app/View/Components/Ui/Modal/ModalLogout.php
<?php

namespace App\View\Components\Ui\Modal;

use Illuminate\View\Component;

class ModalLogout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.ui.modal.modal-logout');
    }
}

app/View/Components/Ui/SideBar.php
<?php

namespace App\View\Components\Ui;

use Illuminate\View\Component;

class SideBar extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.ui.side-bar');
    }
}

app/View/Components/Ui/TopBar.php
<?php

namespace App\View\Components\Ui;

use Illuminate\View\Component;

class TopBar extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.ui.top-bar');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/index.blade.php
@extends('layouts.app')

@section("content")
<div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Dropdown Header:</div>
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            <div class="chart-pie pt-4 pb-2"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                <canvas id="myPieChart" width="505" height="220" style="display: block; height: 245px; width: 562px;" class="chartjs-render-monitor"></canvas>
            </div>
            <div class="mt-4 text-center small">
                <span class="mr-2">
                    <i class="fas fa-circle text-primary"></i> Direct
                </span>
                <span class="mr-2">
                    <i class="fas fa-circle text-success"></i> Social
                </span>
                <span class="mr-2">
                    <i class="fas fa-circle text-info"></i> Referral
                </span>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0">
    <meta http-equiv="pragma" content="no-cache">

    <title>@yield('title')</title>

    <!-- Custom fonts for this template-->
    <link href="{{asset("vendor/fontawesome-free/css/all.min.css")}}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <!-- Custom styles for this template-->
    <link href="{{asset("css/sb-admin-2.min.css")}}" rel="stylesheet">
    <link href="{{asset("css/main.css")}}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <x-side-bar/>

        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <x-top-bar/>
                
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid wrapper">

                    <!-- Page Heading -->


                    <!-- Content Row -->
                    

                        @yield('content')
                        
                    
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <x-modal-logout />

    <!-- Bootstrap core JavaScript-->
    <script src="{{asset("vendor/jquery/jquery.min.js")}}"></script>
    <script src="{{asset("vendor/bootstrap/js/bootstrap.bundle.min.js")}}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{asset("vendor/jquery-easing/jquery.easing.min.js")}}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{asset("js/sb-admin-2.min.js")}}"></script>

    <!-- Page level plugins -->
    <script src="{{asset("vendor/chart.js/Chart.min.js")}}"></script>
    <script src="{{ asset('/vendor/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('/assets/js/plugin/sweetalert/sweetalert.min.js') }}"></script>


    <script src="{{ asset('/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{{ asset('vendor/jquery.blockUI.js') }}"></script>


    <!-- Page level custom scripts -->
    <script src="{{asset("js/app.js")}}"></script>
    @yield('scripts')

</body>

</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/master/barang/create.blade.php
@extends('layouts.app')
@section('title', 'Master Barang')

@section('content')

<div class="row">
    <div class="col-lg-8">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Add Barang</h6>
            </div>
            <div class="card-body">
                <form action="" id="frmEntry" onsubmit="return false">
                    <div class="row" id="boxEntry" >
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Kode Barang <span class="text-danger">*</span></label>
                          <input type="text" class="form-control " id="kode_brang" readonly placeholder="Auto">
                          <div class="invalid-feedback">
                            
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Nama Barang <span class="text-danger">*</span></label>
                          <input type="text" class="form-control" maxlength="30" id="nama_barang">
                          <div class="invalid-feedback">
                            
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Stok </label>
                          <input type="number" class="form-control"   id="stock">
                          <div class="invalid-feedback">
                            
                          </div>
                        </div>
                      </div>

  
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Upload Foto Barang <span class="text-danger">*</span></label>
                          <!-- <input type="file" class="form-control"  required> -->
                          <div class="row">
                            <div class="col-12 text-center">
                              <label class="label-input-file" for="barang_logo">
                                <input type="file" id="barang_logo" accept="image/x-png,image/jpeg, image/png" >
                                <img src="/img/upload.png" data-default-src="/img/upload.png" width="48" class="img-input-file" alt="input-file">
                                <p class="input-file-text" data-default-label="Unggah Foto">Unggah Foto</p>
                              </label>
                              <div class="invalid-feedback">
                            
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
   
                      <div class="col-12">
                        <div class="d-flex justify-content-center">
                          <button class="btn btn-success mr-1">Save</button>
                          <a href='{{ url("barang") }}' id="btn-cancel" type="button" class="btn btn-outline-danger">Cancel</a>
                        </div>
                      </div>
                    </div>
                  </form>
                
            </div>
        </div>
    </div>
</div>


@endsection

@section("scripts")
<script>
$(function() {

    $(".file-upload").on('dragenter', function(e) {
        $(this).parent().addClass('drag-enter')
    })
    $(".file-upload").on('dragleave drop', function() {
        $(this).parent().removeClass('drag-enter')
    })

    $("#logo_bank").on('change', function() {
        handleUploadFile('#logo_bank', {
            allowedFileType: ['jpg', 'jpeg', 'png'], // file extension (without dots)
            limitSize: 5 // in MB
        })
    })


    $('#frmEntry').submit(function(e){
        var formData = new FormData();
        $.each($('#boxEntry :input').serializeObject(), function(x, y){ 
            formData.append(x,y) 
        });
        formData.append('barang_logo',  (typeof $("#barang_logo")[0] == "undefined") ?"":$("#barang_logo")[0].files[0]);
        

        ajax({
            url : "{{ route("barang.store")}}", 
            postData : formData,
            processData: false,
            contentType: false,
            success : function(ret){
                window.location = "{{ url("barang") }}";
            }
        });
        return false;
    })
});	
</script>

@endsection

resources/views/master/barang/edit.blade.php
@extends('layouts.app')
@section('title', 'Master Barang')

@section('content')

<div class="row">
    <div class="col-lg-8">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Edit Barang</h6>
            </div>
            <div class="card-body">
                <form action="" id="frmEntry" onsubmit="return false">
                    <div class="row" id="boxEntry" >
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Kode Barang <span class="text-danger">*</span></label>
                          <input type="text" class="form-control " id="kode_brang" readonly placeholder="Auto" value="{{$data->kode_barang}}">
                          <div class="invalid-feedback">
                            
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Nama Barang <span class="text-danger">*</span></label>
                          <input type="text" class="form-control" maxlength="30" id="nama_barang" value="{{$data->nama_barang}}">
                          <div class="invalid-feedback">
                            
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Stok </label>
                          <input type="number" class="form-control"   id="stock" value="{{$data->stock}}">
                          <div class="invalid-feedback">
                            
                          </div>
                        </div>
                      </div>

  
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Upload Foto Barang <span class="text-danger">*</span></label>
                          <!-- <input type="file" class="form-control"  required> -->
                          <div class="row">
                            <div class="col-12 text-center">
                              <label class="label-input-file" for="barang_logo">
                                <input type="file" id="barang_logo" accept="image/x-png,image/jpeg, image/png" >
                                <img src="/img/upload.png" data-default-src="/img/upload.png" width="48" class="img-input-file" alt="input-file">
                                <p class="input-file-text" data-default-label="Unggah Foto">Unggah Foto</p>
                              </label>
                              <div class="invalid-feedback">
                            
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
   
                      <div class="col-12">
                        <div class="d-flex justify-content-center">
                          <button class="btn btn-success mr-1">Save</button>
                          <a href='{{ url("barang") }}' id="btn-cancel" type="button" class="btn btn-outline-danger">Cancel</a>
                        </div>
                      </div>
                    </div>
                  </form>
                
            </div>
        </div>
    </div>
</div>


@endsection

@section("scripts")
<script>
$(function() {

    $(".file-upload").on('dragenter', function(e) {
        $(this).parent().addClass('drag-enter')
    })
    $(".file-upload").on('dragleave drop', function() {
        $(this).parent().removeClass('drag-enter')
    })

    $("#logo_bank").on('change', function() {
        handleUploadFile('#logo_bank', {
            allowedFileType: ['jpg', 'jpeg', 'png'], // file extension (without dots)
            limitSize: 5 // in MB
        })
    })


    $('#frmEntry').submit(function(e){
        var formData = new FormData();
        $.each($('#boxEntry :input').serializeObject(), function(x, y){ 
            formData.append(x,y) 
        });
        formData.append('barang_logo',  (typeof $("#barang_logo")[0] == "undefined") ?"":$("#barang_logo")[0].files[0]);
        formData.append('_method', "put")
        

        ajax({
            url : "{{ route("barang.update", $data->id)}}", 
            postData : formData,
            processData: false,
            contentType: false,
            success : function(ret){
                window.location = "{{ url("barang") }}";
            }
        });
        return false;
    })
});	
</script>

@endsection

resources/views/master/barang/show.blade.php
@extends('layouts.app')
@section('title', 'Master Barang')

@section('content')

<div class="row">
    <div class="col-lg-8">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">view Barang</h6>
            </div>
            <div class="card-body">
                <form action="" id="frmEntry" onsubmit="return false">
                    <div class="row" id="boxEntry" >
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Kode Barang <span class="text-danger">*</span></label>
                          <input type="text" class="form-control " id="kode_brang" readonly placeholder="Auto" value="{{$data->kode_barang}}">
                          <div class="invalid-feedback">
                            
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Nama Barang <span class="text-danger">*</span></label>
                          <input type="text" class="form-control" maxlength="30" id="nama_barang" value="{{$data->nama_barang}}" readonly>
                          <div class="invalid-feedback">
                            
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Stok </label>
                          <input type="number" class="form-control"   id="stock" value="{{$data->stock}}" readonly>
                          <div class="invalid-feedback">
                            
                          </div>
                        </div>
                      </div>

  
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="">Upload Foto Barang <span class="text-danger">*</span></label>
                          <!-- <input type="file" class="form-control"  required> -->
                          <div class="row">
                            <div class="col-12 text-center">
                              <label class="label-input-file" for="barang_logo">
                                <input type="file" id="barang_logo" accept="image/x-png,image/jpeg, image/png" readonly>
                                <img src="{{$data->img_barang}}" data-default-src="/img/upload.png" width="48" class="img-input-file" alt="input-file">
                                <p class="input-file-text" data-default-label="Unggah Foto">Unggah Foto</p>
                              </label>
                              <div class="invalid-feedback">
                            
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
   
                      <div class="col-12">
                        <div class="d-flex justify-content-center">
                          
                          <a href='{{ url("barang") }}' id="btn-cancel" type="button" class="btn btn-outline-danger">back</a>
                        </div>
                      </div>
                    </div>
                  </form>
                
            </div>
        </div>
    </div>
</div>


@endsection

@section("scripts")
<script>
$(function() {

    $(".file-upload").on('dragenter', function(e) {
        $(this).parent().addClass('drag-enter')
    })
    $(".file-upload").on('dragleave drop', function() {
        $(this).parent().removeClass('drag-enter')
    })

    $("#logo_bank").on('change', function() {
        handleUploadFile('#logo_bank', {
            allowedFileType: ['jpg', 'jpeg', 'png'], // file extension (without dots)
            limitSize: 5 // in MB
        })
    })


    $('#frmEntry').submit(function(e){
        var formData = new FormData();
        $.each($('#boxEntry :input').serializeObject(), function(x, y){ 
            formData.append(x,y) 
        });
        formData.append('barang_logo',  (typeof $("#barang_logo")[0] == "undefined") ?"":$("#barang_logo")[0].files[0]);
        formData.append('_method', "put")
        

        ajax({
            url : "{{ route("barang.update", $data->id)}}", 
            postData : formData,
            processData: false,
            contentType: false,
            success : function(ret){
                window.location = "{{ url("barang") }}";
            }
        });
        return false;
    })
});	
</script>

@endsection